--- #YAML:1.0
name:                Stack-Persistent
version:             0.04
abstract:            A persistent stack
license:             ~
author:              
    - Kevin L. Esteb <kesteb@wsipc.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cache::FastMmap:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
